version: '3'
services:
  postgres: 
    image: "postgres:latest" # Get the Postgres latest image from docker hub
  redis:
    image: "redis:latest" # Get the Redis latest image from docker hub
  server:
    build:
      dockerfile: Dockerfile.dev 
      context: ./server
    volume:
      - /app/node_modules # Keep node modules file as it is
      - ./server:/app # Get all values from server folder except node_modules
    environments: # varName=value
      - REDIS_HOST=redis # indicates the redis server of our docker compose file
      - REDIS_PORT=6379 # default port as per docs
      - PGUSER=postgres # indicates the postgres server of our docker compose file
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password # as per docs in docker hub
      - PGPORT=5432
