version: '3'
services:
  nginx:
    restart: always # If the nginx service crashes, restart it
    build:
      dockerfile: Dockerfile.dev 
      context: ./nginx
    ports:
      - '3050:80' # In dev machine the port is 3050, in container, the port is 80
  postgres: 
    image: "postgres:latest" # Get the Postgres latest image from docker hub
  redis:
    image: "redis:latest" # Get the Redis latest image from docker hub
  api:
    build:
      dockerfile: Dockerfile.dev 
      context: ./server
    volumes:
      - /app/node_modules # Keep node modules file as it is
      - ./server:/app # Get all values from server folder except node_modules
    environment: # varName=value
      - REDIS_HOST=redis # indicates the redis server of our docker compose file
      - REDIS_PORT=6379 # default port as per docs
      - PGUSER=postgres # indicates the postgres server of our docker compose file
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password # as per docs in docker hub
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev 
      context: ./client
    volumes:
      - /app/node_modules # Keep node modules file as it is
      - ./client:/app # Get all values from client folder except node_modules
  worker:
    build:
      dockerfile: Dockerfile.dev 
      context: ./worker
    volumes:
      - /app/node_modules # Keep node modules file as it is
      - ./worker:/app # Get all values from worker folder except node_modules